{
 "title": "Starlink",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dish ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_device_info", "legendFormat": "{{ id }}" }
   ]
  },
  {
   "title": "Dish Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_device_info", "legendFormat": "{{ software_version }}" }
   ]
  },
  {
   "title": "∅ SNR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "starlink_dish_snr" }
   ]
  },
  {
   "title": "∅ Ping Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - starlink_dish_pop_ping_drop_rate OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Dish Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_device_info", "legendFormat": "{{ hardware_version }}" }
   ]
  },
  {
   "title": "Cell ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_cell_id" }
   ]
  },
  {
   "title": "Pop Rack ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_pop_rack_id" }
   ]
  },
  {
   "title": "Country Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_device_info", "legendFormat": "{{ country_code }}" }
   ]
  },
  {
   "title": "Dish State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_state" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dish_uptime_s" }
   ]
  },
  {
   "title": "Seconds to Slot End",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_seconds_to_slot_end"
    }
   ]
  },
  {
   "title": "Seconds to First Non-empty Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_seconds_to_first_nonempty_slot"
    }
   ]
  },
  {
   "title": "Currently Obstructed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_currently_obstructed"
    }
   ]
  },
  {
   "title": "Fraction Obstructed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_fraction_obstructed"
    }
   ]
  },
  {
   "title": "Obstructed Last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_last_24h_obstructed_s"
    }
   ]
  },
  {
   "title": "Obstruction Valid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_valid_s"
    }
   ]
  },
  {
   "title": "Downlink Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(starlink_dish_downlink_throughput_bps) by (id)",
     "legendFormat": "Dish"
    }
   ]
  },
  {
   "title": "Uplink Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(starlink_dish_uplink_throughput_bps) by (id)",
     "legendFormat": "Dish"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(starlink_dish_pop_ping_latency_ms) by (id)",
     "legendFormat": "Dish"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Motors Stuck",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_alert_motors_stuck",
     "legendFormat": "Dish {{ id }}"
    }
   ]
  },
  {
   "title": "Thermal Throttle",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_alert_thermal_throttle",
     "legendFormat": "Dish {{ id }}"
    }
   ]
  },
  {
   "title": "Thermal Shutdown",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_alert_thermal_shutdown",
     "legendFormat": "Dish {{ id }}"
    }
   ]
  },
  {
   "title": "Mast Not Near Vertical",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_alert_mast_not_near_vertical",
     "legendFormat": "Dish {{ id }}"
    }
   ]
  },
  {
   "title": "Unexpected Location",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_alert_unexpected_location",
     "legendFormat": "Dish {{ id }}"
    }
   ]
  },
  {
   "title": "Slow Ethernet Speeds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_alert_slow_ethernet_speeds",
     "legendFormat": "Dish {{ id }}"
    }
   ]
  }
 ]
}